name: Release

on:
  push:
    branches:
      - main
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: Semver
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          ci: false
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/git
            @semantic-release/github

      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: sammobach/gitdesk-forwarder:${{ steps.release.outputs.new_release_version }}
          cache: true
          cache-repository: sammobach/gitdesk-forwarder/cache

      - name: Do something when a new release published
        if: steps.release.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.release.outputs.new_release_version }}
          echo ${{ steps.release.outputs.new_release_major_version }}
          echo ${{ steps.release.outputs.new_release_minor_version }}
          echo ${{ steps.release.outputs.new_release_patch_version }}